const recettes = [
  {
    id: 1,
    title: 'Tagliatelles au Saumon et Curry',
    description:
      'Un plat savoureux et crémeux alliant tagliatelles, saumon et épices pour une touche exotique.',
    country: 'Italie',
    image:
      require('../assets/images/tagliatèle_saumon_curry.webp'),
    time: '1h',
    prepTime: '15min',
    cookTime: '45min',
    difficulty: 'Facile',
    rating: 4.6,
    reviews: 89,
    category: 'Plat principal',
    servings: 4,
    tags: ['crémeux', 'poisson', 'rapide'],
    ingredients: [
      { name: 'Tagliatelles', quantity: '400g', category: 'Céréales' },
      {
        name: 'Pavés de saumon surgelés',
        quantity: '2 pièces',
        category: 'Poissons',
      },
      {
        name: 'Échalotes hachées',
        quantity: '1 c. à soupe',
        category: 'Condiments',
      },
      { name: 'Curry', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Paprika', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Poivre', quantity: '1 c. à café', category: 'Épices' },
      {
        name: 'Crème fraîche',
        quantity: '20cl',
        category: 'Produits laitiers',
      },
      { name: 'Tomates cerises', quantity: '4 pièces', category: 'Légumes' },
      {
        name: 'Huile d’olive',
        quantity: '1 filet',
        category: 'Matières grasses',
      },
      { name: 'Sel', quantity: '1 pincée', category: 'Épices' },
    ],
    steps: [
      {
        number: 1,
        title: 'Préparation du saumon',
        description:
          "Faites décongeler les pavés de saumon, puis faites-les revenir 5 minutes à la poêle avec un filet d'huile d'olive, sel et poivre.",
        duration: '10min',
        tips: 'Ne cuisez pas trop le saumon pour qu’il reste tendre.',
      },
      {
        number: 2,
        title: 'Préparation de la sauce',
        description:
          'Dans une sauteuse, faites fondre les échalotes, ajoutez curry, paprika, ail, crème fraîche. Laissez réduire 10 minutes à feu doux.',
        duration: '15min',
        tips: 'Remuez régulièrement pour éviter que la crème accroche.',
      },
      {
        number: 3,
        title: 'Cuisson des pâtes',
        description:
          "Faites cuire les tagliatelles dans de l'eau bouillante salée, égouttez-les puis ajoutez-les dans la sauteuse avec la sauce.",
        duration: '10min',
        tips: 'Gardez un peu d’eau de cuisson pour lier la sauce si nécessaire.',
      },
      {
        number: 4,
        title: 'Assemblage final',
        description:
          'Ajoutez le saumon et les tomates cerises à la préparation, mélangez délicatement et servez.',
        duration: '10min',
        tips: 'Ajoutez un filet de citron pour rehausser le goût du saumon.',
      },
    ],
    nutrition: {
      calories: 580,
      protein: 32,
      carbs: 50,
      fat: 28,
      fiber: 4,
    },
    tips: [
      'Vous pouvez remplacer le saumon par du poulet ou des crevettes.',
      'Ajoutez du parmesan râpé au moment de servir pour plus de goût.',
      'Utilisez des tagliatelles fraîches pour une meilleure texture.',
    ],
  },
  {
    id: 2,
    title: 'Frites aux Lardons et Viande Hachée',
    description:
      'Un plat réconfortant à base de frites maison, viande hachée, lardons et sauce au fromage fondant.',
    country: 'France',
    image:
      require('../assets/images/frites_lardons.webp'),
    time: '1h',
    prepTime: '20min',
    cookTime: '40min',
    difficulty: 'Facile',
    rating: 4.5,
    reviews: 102,
    category: 'Plat principal',
    servings: 4,
    tags: ['fromagé', 'comfort food', 'rapide'],
    chef: 'Chef Lucas',
    ingredients: [
      { name: 'Pommes de terre', quantity: '4', category: 'Légumes' },
      { name: 'Huile', quantity: 'pour friture', category: 'Matières grasses' },
      { name: 'Lait', quantity: '1 verre', category: 'Liquides' },
      { name: 'Cheddar', quantity: '100g', category: 'Produits laitiers' },
      { name: 'Gruyère râpé', quantity: '100g', category: 'Produits laitiers' },
      { name: 'Épices plein sud', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Épices douces', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Bouillon magique', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Paprika fumé', quantity: '1 pincée', category: 'Épices' },
      { name: 'Poivre', quantity: '1 pincée', category: 'Épices' },
      { name: 'Oignon', quantity: '1', category: 'Légumes' },
      { name: 'Ail émincé', quantity: '2 gousses', category: 'Condiments' },
      { name: 'Persil frais', quantity: '1 c. à café', category: 'Herbes' },
      { name: 'Viande hachée', quantity: '200g', category: 'Viandes' },
      { name: 'Lardons', quantity: '100g', category: 'Viandes' },
    ],
    steps: [
      {
        number: 1,
        title: 'Préparation des frites',
        description:
          'Coupez les pommes de terre en frites, faites-les frire et réservez sur du papier absorbant.',
        duration: '20min',
        tips: 'Faites deux bains de cuisson pour plus de croustillant.',
      },
      {
        number: 2,
        title: 'Cuisson des oignons',
        description:
          'Faites revenir les oignons avec les épices jusqu’à ce qu’ils caramélisent.',
        duration: '15min',
        tips: 'Remuez souvent pour ne pas brûler les oignons.',
      },
      {
        number: 3,
        title: 'Cuisson des viandes',
        description:
          'Faites dorer les lardons, réservez. Puis faites cuire la viande hachée avec les mêmes épices.',
        duration: '15min',
        tips: 'Mélangez bien pour que les arômes se répartissent.',
      },
      {
        number: 4,
        title: 'Préparation de la sauce',
        description:
          'Faites fondre le cheddar et le gruyère dans le lait jusqu’à obtenir une sauce crémeuse.',
        duration: '10min',
        tips: 'Ajoutez un peu de lait si la sauce est trop épaisse.',
      },
      {
        number: 5,
        title: 'Assemblage',
        description:
          'Disposez les frites, ajoutez viande, lardons, oignons et nappez de sauce. Parsemez de persil.',
        duration: '5min',
        tips: 'Servez immédiatement pour garder le croustillant des frites.',
      },
    ],
    nutrition: {
      calories: 730,
      protein: 29,
      carbs: 60,
      fat: 45,
      fiber: 6,
    },
    tips: [
      'Utilisez un fromage plus fort comme le bleu pour varier.',
      'Ajoutez du piment pour une version relevée.',
      "Servez avec une salade verte pour l'équilibre.",
    ],
  },
  {
    id: 3,
    title: 'Boulettes de Poulet Sauce Crémeuse',
    description:
      'Des boulettes moelleuses de poulet dans une sauce onctueuse aux épinards et tomates cerises.',
    country: 'France',
    image:
      require('../assets/images/boulettes_poulet.webp'),
    time: '45min',
    prepTime: '20min',
    cookTime: '25min',
    difficulty: 'Intermédiaire',
    rating: 4.7,
    reviews: 76,
    category: 'Plat principal',
    servings: 3,
    tags: ['boulettes', 'crème', 'léger'],
    chef: 'Chef Samira',
    ingredients: [
      { name: 'Blancs de poulet', quantity: '100g', category: 'Viandes' },
      { name: 'Oignon', quantity: '1/2', category: 'Légumes' },
      { name: 'Ail', quantity: '1 gousse', category: 'Condiments' },
      { name: 'Œuf', quantity: '1', category: 'Produits frais' },
      { name: 'Chapelure', quantity: '2 c. à soupe', category: 'Céréales' },
      { name: 'Persil frais', quantity: '1 c. à soupe', category: 'Herbes' },
      { name: 'Huile', quantity: '1 filet', category: 'Matières grasses' },
      { name: 'Sel aromatisé', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Poivre', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Paprika fumé', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Ail fumé', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Cumin', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Épices du Sud', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Fond de veau', quantity: '1 c. à café', category: 'Épices' },
      { name: 'Maïzena', quantity: '1 c. à café', category: 'Épaississants' },
      {
        name: 'Crème fraîche épaisse',
        quantity: '2 c. à soupe',
        category: 'Produits laitiers',
      },
      {
        name: "Feuilles d'épinards",
        quantity: '1 poignée',
        category: 'Légumes',
      },
      { name: 'Tomates cerises', quantity: '4 pièces', category: 'Légumes' },
    ],
    steps: [
      {
        number: 1,
        title: 'Préparation des boulettes',
        description:
          'Mixez les blancs de poulet avec oignon, ail, persil, épices, œuf, chapelure et huile. Formez des boulettes.',
        duration: '10min',
        tips: 'Ajoutez un peu de chapelure si la pâte est trop humide.',
      },
      {
        number: 2,
        title: 'Cuisson des boulettes',
        description:
          'Faites dorer les boulettes 2 minutes de chaque côté dans une poêle chaude.',
        duration: '5min',
        tips: 'Ne surchargez pas la poêle pour une cuisson uniforme.',
      },
      {
        number: 3,
        title: 'Préparation de la sauce',
        description:
          'Faites revenir oignon et ail, ajoutez fond de veau, Maïzena diluée, crème, épices. Faites mijoter.',
        duration: '10min',
        tips: 'La sauce doit être lisse et nappante.',
      },
      {
        number: 4,
        title: 'Ajout des légumes et finition',
        description:
          'Ajoutez les épinards et tomates cerises, remettez les boulettes et laissez mijoter quelques minutes.',
        duration: '10min',
        tips: 'Couvrez pour bien cuire les légumes à la vapeur.',
      },
    ],
    nutrition: {
      calories: 430,
      protein: 30,
      carbs: 18,
      fat: 28,
      fiber: 3,
    },
    tips: [
      'Servez avec du riz ou de la semoule pour un repas complet.',
      'Ajoutez du parmesan dans la sauce pour plus de saveur.',
      "Les boulettes peuvent être préparées à l'avance et congelées.",
    ],
  },
/*   {
    id: 8,
    title: 'Tagliatelles au saumon et au curry',
    description:
      'Un plat raffiné et original qui marie la douceur du saumon à la chaleur du curry, servi avec des tagliatelles fondantes. Parfait pour un repas convivial ou une occasion spéciale.',
    country: 'Italien',
    image:
      'https://images.pexels.com/photos/6210959/pexels-photo-6210959.jpeg?auto=compress&cs=tinysrgb&w=600',
    time: '1 heure',
    difficulty: 'Intermédiaire',
    rating: 4.5,
    category: 'Plat principal',
    servings: 4,
    tags: ['épicé', 'crémeux', 'poisson', 'pâtes'],
  },
  {
    id: 9,
    title: 'Pad Thaï Authentique',
    description: 'Nouilles sautées thaïlandaises avec crevettes et cacahuètes',
    country: 'Thaïlande',
    image:
      'https://images.pexels.com/photos/4958792/pexels-photo-4958792.jpeg?auto=compress&cs=tinysrgb&w=600',
    time: '25min',
    difficulty: 'Facile',
    rating: 4.9,
    category: 'Plat principal',
    servings: 4,
    tags: ['rapide', 'asiatique', 'nouilles'],
  },
  {
    id: 10,
    title: 'Tiramisu Italien',
    description: 'Le dessert italien emblématique, crémeux et parfumé',
    country: 'Italie',
    image:
      'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg?auto=compress&cs=tinysrgb&w=600',
    time: '4h',
    difficulty: 'Facile',
    rating: 4.7,
    category: 'Dessert',
    servings: 8,
    tags: ['café', 'crémeux', 'italien'],
  },
  {
    id: 4,
    title: 'Sushi Maki Maison',
    description: 'Apprenez à préparer des sushis comme un chef japonais',
    country: 'Japon',
    image:
      'https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg?auto=compress&cs=tinysrgb&w=600',
    time: '1h 30min',
    difficulty: 'Difficile',
    rating: 4.6,
    category: 'Entrée',
    servings: 4,
    tags: ['japonais', 'poisson', 'technique'],
  },
  {
    id: 5,
    title: 'Paella Valencienne',
    description: 'La vraie recette espagnole avec safran et fruits de mer',
    country: 'Espagne',
    image:
      'https://images.pexels.com/photos/16743294/pexels-photo-16743294.jpeg?auto=compress&cs=tinysrgb&w=600',
    time: '45min',
    difficulty: 'Intermédiaire',
    rating: 4.8,
    category: 'Plat principal',
    servings: 6,
    tags: ['riz', 'fruits de mer', 'safran'],
  },
  {
    id: 6,
    title: 'Baklava Turc',
    description: 'Pâtisserie feuilletée aux noix et sirop de miel',
    country: 'Turquie',
    image:
      'https://images.pexels.com/photos/7474467/pexels-photo-7474467.jpeg?auto=compress&cs=tinysrgb&w=600',
    time: '2h',
    difficulty: 'Intermédiaire',
    rating: 4.5,
    category: 'Dessert',
    servings: 12,
    tags: ['sucré', 'noix', 'miel'],
  }, */
];

export default recettes;
